spring:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver


server:
  port: 8080
